<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Software extends \App\Entity\Software implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Software' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Software' . "\0" . 'title', '' . "\0" . 'App\\Entity\\Software' . "\0" . 'pageurl', '' . "\0" . 'App\\Entity\\Software' . "\0" . 'totallinkedcasinos', '' . "\0" . 'App\\Entity\\Software' . "\0" . 'timeaded', '' . "\0" . 'App\\Entity\\Software' . "\0" . 'timeupdated', '' . "\0" . 'App\\Entity\\Software' . "\0" . 'imagelink', '' . "\0" . 'App\\Entity\\Software' . "\0" . 'uploadedimagelink', '' . "\0" . 'App\\Entity\\Software' . "\0" . 'imgsrc', '' . "\0" . 'App\\Entity\\Software' . "\0" . 'casinos', '' . "\0" . 'App\\Entity\\Software' . "\0" . 'restrictedcountries', '' . "\0" . 'App\\Entity\\Software' . "\0" . 'softwareslist', '' . "\0" . 'App\\Entity\\Software' . "\0" . 'availableInCountry', '' . "\0" . 'App\\Entity\\Software' . "\0" . 'softwarelogo', '' . "\0" . 'App\\Entity\\Software' . "\0" . 'image25'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Software' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Software' . "\0" . 'title', '' . "\0" . 'App\\Entity\\Software' . "\0" . 'pageurl', '' . "\0" . 'App\\Entity\\Software' . "\0" . 'totallinkedcasinos', '' . "\0" . 'App\\Entity\\Software' . "\0" . 'timeaded', '' . "\0" . 'App\\Entity\\Software' . "\0" . 'timeupdated', '' . "\0" . 'App\\Entity\\Software' . "\0" . 'imagelink', '' . "\0" . 'App\\Entity\\Software' . "\0" . 'uploadedimagelink', '' . "\0" . 'App\\Entity\\Software' . "\0" . 'imgsrc', '' . "\0" . 'App\\Entity\\Software' . "\0" . 'casinos', '' . "\0" . 'App\\Entity\\Software' . "\0" . 'restrictedcountries', '' . "\0" . 'App\\Entity\\Software' . "\0" . 'softwareslist', '' . "\0" . 'App\\Entity\\Software' . "\0" . 'availableInCountry', '' . "\0" . 'App\\Entity\\Software' . "\0" . 'softwarelogo', '' . "\0" . 'App\\Entity\\Software' . "\0" . 'image25'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Software $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setId($id): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', [$id]);

        parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getTimeUpdated()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTimeUpdated', []);

        return parent::getTimeUpdated();
    }

    /**
     * {@inheritDoc}
     */
    public function setTimeUpdated($timeupdated): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTimeUpdated', [$timeupdated]);

        parent::setTimeUpdated($timeupdated);
    }

    /**
     * {@inheritDoc}
     */
    public function setTitle($title): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitle', [$title]);

        parent::setTitle($title);
    }

    /**
     * {@inheritDoc}
     */
    public function getTitle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitle', []);

        return parent::getTitle();
    }

    /**
     * {@inheritDoc}
     */
    public function getCasinos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCasinos', []);

        return parent::getCasinos();
    }

    /**
     * {@inheritDoc}
     */
    public function setCasinos($casinos): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCasinos', [$casinos]);

        parent::setCasinos($casinos);
    }

    /**
     * {@inheritDoc}
     */
    public function getImageLink()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImageLink', []);

        return parent::getImageLink();
    }

    /**
     * {@inheritDoc}
     */
    public function setImageLink($imagelink): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImageLink', [$imagelink]);

        parent::setImageLink($imagelink);
    }

    /**
     * {@inheritDoc}
     */
    public function getTimeAded()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTimeAded', []);

        return parent::getTimeAded();
    }

    /**
     * {@inheritDoc}
     */
    public function setTimeAded($timeaded): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTimeAded', [$timeaded]);

        parent::setTimeAded($timeaded);
    }

    /**
     * {@inheritDoc}
     */
    public function getPageUrl()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPageUrl', []);

        return parent::getPageUrl();
    }

    /**
     * {@inheritDoc}
     */
    public function setPageUrl($pageurl): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPageUrl', [$pageurl]);

        parent::setPageUrl($pageurl);
    }

    /**
     * {@inheritDoc}
     */
    public function getTotalLinkedCasinos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTotalLinkedCasinos', []);

        return parent::getTotalLinkedCasinos();
    }

    /**
     * {@inheritDoc}
     */
    public function setTotalLinkedCasinos($totallinkedcasinos): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTotalLinkedCasinos', [$totallinkedcasinos]);

        parent::setTotalLinkedCasinos($totallinkedcasinos);
    }

    /**
     * {@inheritDoc}
     */
    public function getUploadedImageLink()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUploadedImageLink', []);

        return parent::getUploadedImageLink();
    }

    /**
     * {@inheritDoc}
     */
    public function setUploadedImageLink($uploadedimagelink): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUploadedImageLink', [$uploadedimagelink]);

        parent::setUploadedImageLink($uploadedimagelink);
    }

    /**
     * {@inheritDoc}
     */
    public function addCasino(\App\Entity\Casino $casino): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCasino', [$casino]);

        parent::addCasino($casino);
    }

    /**
     * {@inheritDoc}
     */
    public function getImgsrc()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImgsrc', []);

        return parent::getImgsrc();
    }

    /**
     * {@inheritDoc}
     */
    public function setImgsrc($imgsrc): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImgsrc', [$imgsrc]);

        parent::setImgsrc($imgsrc);
    }

    /**
     * {@inheritDoc}
     */
    public function addRestrictedCountry(\App\Entity\Country $country)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addRestrictedCountry', [$country]);

        return parent::addRestrictedCountry($country);
    }

    /**
     * {@inheritDoc}
     */
    public function getRestrictedcountries()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRestrictedcountries', []);

        return parent::getRestrictedcountries();
    }

    /**
     * {@inheritDoc}
     */
    public function setAvailableInCountry(bool $availableInCountry): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAvailableInCountry', [$availableInCountry]);

        parent::setAvailableInCountry($availableInCountry);
    }

    /**
     * {@inheritDoc}
     */
    public function isAvailableInCountry(): bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isAvailableInCountry', []);

        return parent::isAvailableInCountry();
    }

    /**
     * {@inheritDoc}
     */
    public function getSoftwarelogo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSoftwarelogo', []);

        return parent::getSoftwarelogo();
    }

    /**
     * {@inheritDoc}
     */
    public function setSoftwarelogo($softwarelogo): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSoftwarelogo', [$softwarelogo]);

        parent::setSoftwarelogo($softwarelogo);
    }

    /**
     * {@inheritDoc}
     */
    public function getSoftwareslist()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSoftwareslist', []);

        return parent::getSoftwareslist();
    }

    /**
     * {@inheritDoc}
     */
    public function setSoftwareslist($softwareslist): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSoftwareslist', [$softwareslist]);

        parent::setSoftwareslist($softwareslist);
    }

    /**
     * {@inheritDoc}
     */
    public function getImage25()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImage25', []);

        return parent::getImage25();
    }

    /**
     * {@inheritDoc}
     */
    public function setImage25($image25): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImage25', [$image25]);

        parent::setImage25($image25);
    }

}
