<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class ArticleCategory extends \App\Entity\ArticleCategory implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\ArticleCategory' . "\0" . 'id', '' . "\0" . 'App\\Entity\\ArticleCategory' . "\0" . 'name', '' . "\0" . 'App\\Entity\\ArticleCategory' . "\0" . 'introText', '' . "\0" . 'App\\Entity\\ArticleCategory' . "\0" . 'articles', '' . "\0" . 'App\\Entity\\ArticleCategory' . "\0" . 'news', '' . "\0" . 'App\\Entity\\ArticleCategory' . "\0" . 'slug', '' . "\0" . 'App\\Entity\\ArticleCategory' . "\0" . 'imgsrc', '' . "\0" . 'App\\Entity\\ArticleCategory' . "\0" . 'file', '' . "\0" . 'App\\Entity\\ArticleCategory' . "\0" . 'imglocation'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\ArticleCategory' . "\0" . 'id', '' . "\0" . 'App\\Entity\\ArticleCategory' . "\0" . 'name', '' . "\0" . 'App\\Entity\\ArticleCategory' . "\0" . 'introText', '' . "\0" . 'App\\Entity\\ArticleCategory' . "\0" . 'articles', '' . "\0" . 'App\\Entity\\ArticleCategory' . "\0" . 'news', '' . "\0" . 'App\\Entity\\ArticleCategory' . "\0" . 'slug', '' . "\0" . 'App\\Entity\\ArticleCategory' . "\0" . 'imgsrc', '' . "\0" . 'App\\Entity\\ArticleCategory' . "\0" . 'file', '' . "\0" . 'App\\Entity\\ArticleCategory' . "\0" . 'imglocation'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (ArticleCategory $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setName($name): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', [$name]);

        parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', []);

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function getArticles()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArticles', []);

        return parent::getArticles();
    }

    /**
     * {@inheritDoc}
     */
    public function getNews()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNews', []);

        return parent::getNews();
    }

    /**
     * {@inheritDoc}
     */
    public function getSlug()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSlug', []);

        return parent::getSlug();
    }

    /**
     * {@inheritDoc}
     */
    public function getImgsrc()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImgsrc', []);

        return parent::getImgsrc();
    }

    /**
     * {@inheritDoc}
     */
    public function setImgsrc($imgsrc): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImgsrc', [$imgsrc]);

        parent::setImgsrc($imgsrc);
    }

    /**
     * {@inheritDoc}
     */
    public function getFile()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFile', []);

        return parent::getFile();
    }

    /**
     * {@inheritDoc}
     */
    public function setFile($file): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFile', [$file]);

        parent::setFile($file);
    }

    /**
     * {@inheritDoc}
     */
    public function getImglocation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImglocation', []);

        return parent::getImglocation();
    }

    /**
     * {@inheritDoc}
     */
    public function setImglocation($imglocation): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImglocation', [$imglocation]);

        parent::setImglocation($imglocation);
    }

    /**
     * {@inheritDoc}
     */
    public function getIntroText(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIntroText', []);

        return parent::getIntroText();
    }

    /**
     * {@inheritDoc}
     */
    public function setIntroText(?string $introText): \App\Entity\ArticleCategory
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIntroText', [$introText]);

        return parent::setIntroText($introText);
    }

}
