<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.k8IrT0Q' shared service.

return $this->privates['.service_locator.k8IrT0Q'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'countryIconsWebPath' => ['privates', '.value.sce0Niv', 'get_Value_Sce0NivService.php', true],
    'page' => ['privates', '.errored..service_locator.k8IrT0Q.App\\Entity\\MainPage', NULL, 'Cannot autowire service ".service_locator.k8IrT0Q": it references class "App\\Entity\\MainPage" but no such service exists.'],
], [
    'countryIconsWebPath' => '?',
    'page' => 'App\\Entity\\MainPage',
]);
