<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator._3QlCbX' shared service.

return $this->privates['.service_locator._3QlCbX'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'eventDispatcher' => ['services', 'event_dispatcher', 'getEventDispatcherService', false],
    'validator' => ['services', 'validator', 'getValidatorService', false],
], [
    'eventDispatcher' => '?',
    'validator' => '?',
]);
