<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.z6mvegV' shared service.

return $this->privates['.service_locator.z6mvegV'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'googleSignIn' => ['privates', 'App\\RegisterLogin\\GoogleSignIn', 'getGoogleSignInService.php', true],
], [
    'googleSignIn' => 'App\\RegisterLogin\\GoogleSignIn',
]);
