<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.zxbSDfY' shared service.

return $this->privates['.service_locator.zxbSDfY'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'bonusRenderManager' => ['privates', 'App\\BonusRendering\\BonusRenderManager', 'getBonusRenderManagerService.php', true],
], [
    'bonusRenderManager' => 'App\\BonusRendering\\BonusRenderManager',
]);
