<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.r0qH_U.' shared service.

return $this->privates['.service_locator.r0qH_U.'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'awebber' => ['privates', 'App\\Aweber\\MyApp', 'getMyAppService.php', true],
    'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
    'locator' => ['privates', 'App\\Utils\\Locator', 'getLocatorService.php', true],
    'socialRegister' => ['privates', 'App\\SocialRegister\\SocialRegister', 'getSocialRegisterService.php', true],
], [
    'awebber' => 'App\\Aweber\\MyApp',
    'em' => '?',
    'locator' => 'App\\Utils\\Locator',
    'socialRegister' => 'App\\SocialRegister\\SocialRegister',
]);
