<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.OSURPgs' shared service.

return $this->privates['.service_locator.OSURPgs'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'userRegister' => ['privates', 'App\\RegisterLogin\\UserRegister', 'getUserRegisterService.php', true],
], [
    'userRegister' => 'App\\RegisterLogin\\UserRegister',
]);
