<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.PuHm3bS' shared service.

return $this->privates['.service_locator.PuHm3bS'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'article' => ['privates', '.errored..service_locator.PuHm3bS.App\\Entity\\Article', NULL, 'Cannot autowire service ".service_locator.PuHm3bS": it references class "App\\Entity\\Article" but no such service exists.'],
    'textReplacement' => ['privates', 'App\\TextReplacement\\TextReplacement', 'getTextReplacementService.php', true],
], [
    'article' => 'App\\Entity\\Article',
    'textReplacement' => 'App\\TextReplacement\\TextReplacement',
]);
