<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\EntityListener\ArticleCategoryListener' shared autowired service.

include_once \dirname(__DIR__, 4).'/src/EntityListener/ArticleCategoryListener.php';

return $this->privates['App\\EntityListener\\ArticleCategoryListener'] = new \App\EntityListener\ArticleCategoryListener((\dirname(__DIR__, 4).'/public'.$this->getEnv('string:UPLOAD_PATH').'/news-category/'), $this->getEnv('string:UPLOAD_PATH').'/news-category/');
