<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.errored..service_locator.k6c42JM.App\Entity\ArticleCategory' shared service.

include_once \dirname(__DIR__, 4).'/src/Entity/ArticleCategory.php';

return $this->privates['.errored..service_locator.k6c42JM.App\\Entity\\ArticleCategory'] = new \App\Entity\ArticleCategory();
