<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\EntityListener\BankingListener' shared autowired service.

include_once \dirname(__DIR__, 4).'/src/EntityListener/BankingListener.php';

return $this->privates['App\\EntityListener\\BankingListener'] = new \App\EntityListener\BankingListener($this->getEnv('string:UPLOAD_PATH').'/banking/');
