<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\EntityListener\CountryListener' shared autowired service.

include_once \dirname(__DIR__, 4).'/src/EntityListener/CountryListener.php';

return $this->privates['App\\EntityListener\\CountryListener'] = new \App\EntityListener\CountryListener('/images/country/', ($this->services['doctrine.orm.default_entity_manager'] ?? $this->getDoctrine_Orm_DefaultEntityManagerService()));
