<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Repository\CurrenciesRepository' shared autowired service.

include_once \dirname(__DIR__, 4).'/src/Repository/CurrenciesRepository.php';

return $this->privates['App\\Repository\\CurrenciesRepository'] = new \App\Repository\CurrenciesRepository(($this->services['doctrine'] ?? $this->getDoctrineService()));
