<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Repository\CasinoDetailsRepository' shared autowired service.

include_once \dirname(__DIR__, 4).'/src/Repository/CasinoDetailsRepository.php';

return $this->privates['App\\Repository\\CasinoDetailsRepository'] = new \App\Repository\CasinoDetailsRepository(($this->services['doctrine'] ?? $this->getDoctrineService()));
