<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\EntityListener\CasinoListener' shared autowired service.

include_once \dirname(__DIR__, 4).'/src/EntityListener/CasinoListener.php';

return $this->privates['App\\EntityListener\\CasinoListener'] = new \App\EntityListener\CasinoListener(($this->privates['App\\Mailer\\Mailer'] ?? $this->load('getMailerService.php')), $this->getEnv('string:UPLOAD_PATH').'/casino/', $this->getEnv('MELANYS_MAIL'), $this->getEnv('JOSHS_MAIL'));
