<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\EntityListener\GamesListListener' shared autowired service.

include_once \dirname(__DIR__, 4).'/src/EntityListener/GamesListListener.php';

return $this->privates['App\\EntityListener\\GamesListListener'] = new \App\EntityListener\GamesListListener();
