<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Repository\LikesAndPostsRepository' shared autowired service.

include_once \dirname(__DIR__, 4).'/src/Repository/LikesAndPostsRepository.php';

return $this->privates['App\\Repository\\LikesAndPostsRepository'] = new \App\Repository\LikesAndPostsRepository(($this->services['doctrine'] ?? $this->getDoctrineService()));
