<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Mailer\Mailer' shared autowired service.

include_once \dirname(__DIR__, 4).'/src/Mailer/Mailer.php';

return $this->privates['App\\Mailer\\Mailer'] = new \App\Mailer\Mailer(($this->services['swiftmailer.mailer.default'] ?? $this->load('getSwiftmailer_Mailer_DefaultService.php')), ($this->services['request_stack'] ?? ($this->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack())), ($this->services['templating'] ?? $this->load('getTemplatingService.php')), $this->getEnv('JOSHS_MAIL'));
