<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.errored..service_locator.ffIvquG.App\Entity\News' shared service.

include_once \dirname(__DIR__, 4).'/src/Entity/News.php';

return $this->privates['.errored..service_locator.ffIvquG.App\\Entity\\News'] = new \App\Entity\News();
