<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sonata.templating.locator' shared service.

@trigger_error('The "sonata.templating.locator" service is deprecated since sonata-project/block-bundle 3.17 and will be removed in version 4.0.', E_USER_DEPRECATED);

return new \Sonata\BlockBundle\Templating\TemplateLocator(($this->privates['file_locator'] ?? $this->load('getFileLocatorService.php')), $this->targetDir.'');
