<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Repository\SoftwaresListRepository' shared autowired service.

include_once \dirname(__DIR__, 4).'/src/Repository/SoftwaresListRepository.php';

return $this->privates['App\\Repository\\SoftwaresListRepository'] = new \App\Repository\SoftwaresListRepository(($this->services['doctrine'] ?? $this->getDoctrineService()));
