<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.errored..service_locator.KsF9X_Z.App\Entity\SoftwaresList' shared service.

include_once \dirname(__DIR__, 4).'/src/Entity/SoftwaresList.php';

return $this->privates['.errored..service_locator.KsF9X_Z.App\\Entity\\SoftwaresList'] = new \App\Entity\SoftwaresList();
