<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\RegisterLogin\TwitterSignIn' shared autowired service.

include_once \dirname(__DIR__, 4).'/src/RegisterLogin/SocialInterface.php';
include_once \dirname(__DIR__, 4).'/src/RegisterLogin/TwitterSignIn.php';

return $this->privates['App\\RegisterLogin\\TwitterSignIn'] = new \App\RegisterLogin\TwitterSignIn($this->getEnv('TWITTER_CONSUMER_KEY'), $this->getEnv('TWITTER_CONSUMER_SECRET'), $this->getEnv('TWITTER_REDIRECT_URI'), ($this->services['session'] ?? $this->load('getSessionService.php')), ($this->services['doctrine.orm.default_entity_manager'] ?? $this->getDoctrine_Orm_DefaultEntityManagerService()), ($this->services['request_stack'] ?? ($this->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack())));
