<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\RegisterLogin\UserRegister' shared autowired service.

include_once \dirname(__DIR__, 4).'/src/RegisterLogin/UserRegister.php';
include_once \dirname(__DIR__, 4).'/src/Encoders/SaltMaker.php';

return $this->privates['App\\RegisterLogin\\UserRegister'] = new \App\RegisterLogin\UserRegister(($this->services['doctrine.orm.default_entity_manager'] ?? $this->getDoctrine_Orm_DefaultEntityManagerService()), ($this->services['security.password_encoder'] ?? $this->load('getSecurity_PasswordEncoderService.php')), ($this->privates['App\\Encoders\\SaltMaker'] ?? ($this->privates['App\\Encoders\\SaltMaker'] = new \App\Encoders\SaltMaker())), ($this->privates['App\\Mailer\\Mailer'] ?? $this->load('getMailerService.php')), ($this->services['request_stack'] ?? ($this->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack())));
