<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.value.sce0Niv' shared service.

return $this->privates['.value.sce0Niv'] = \current([0 => '/images/country/']);
