<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.WUSGIKP' shared service.

return $this->privates['.service_locator.WUSGIKP'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'countryList' => ['privates', '.errored..service_locator.WUSGIKP.App\\Entity\\CountryList', NULL, 'Cannot autowire service ".service_locator.WUSGIKP": it references class "App\\Entity\\CountryList" but no such service exists.'],
    'countryPage' => ['privates', '.errored..service_locator.WUSGIKP.App\\Entity\\CountryList', NULL, 'Cannot autowire service ".service_locator.WUSGIKP": it references class "App\\Entity\\CountryList" but no such service exists.'],
], [
    'countryList' => 'App\\Entity\\CountryList',
    'countryPage' => 'App\\Entity\\CountryList',
]);
