<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.k6c42JM' shared service.

return $this->privates['.service_locator.k6c42JM'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'articleCategory' => ['privates', '.errored..service_locator.k6c42JM.App\\Entity\\ArticleCategory', NULL, 'Cannot autowire service ".service_locator.k6c42JM": it references class "App\\Entity\\ArticleCategory" but no such service exists.'],
], [
    'articleCategory' => 'App\\Entity\\ArticleCategory',
]);
