<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.IY8fuuf' shared service.

return $this->privates['.service_locator.IY8fuuf'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
    'mail' => ['privates', 'App\\Mailer\\Mailer', 'getMailerService.php', true],
    'validator' => ['services', 'validator', 'getValidatorService', false],
], [
    'em' => '?',
    'mail' => 'App\\Mailer\\Mailer',
    'validator' => '?',
]);
