<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.yfEj2hU' shared service.

return $this->privates['.service_locator.yfEj2hU'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'bonusValuePage' => ['privates', '.errored..service_locator.yfEj2hU.App\\Entity\\BonusValue', NULL, 'Cannot autowire service ".service_locator.yfEj2hU": it references class "App\\Entity\\BonusValue" but no such service exists.'],
], [
    'bonusValuePage' => 'App\\Entity\\BonusValue',
]);
