<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.7BynSmk' shared service.

return $this->privates['.service_locator.7BynSmk'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'countryIconsWebPath' => ['privates', '.value.sce0Niv', 'get_Value_Sce0NivService.php', true],
    'es' => ['privates', 'App\\ElasticSearch\\ElasticSearch', 'getElasticSearchService.php', true],
], [
    'countryIconsWebPath' => '?',
    'es' => 'App\\ElasticSearch\\ElasticSearch',
]);
