<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.3hf0Uq0' shared service.

return $this->privates['.service_locator.3hf0Uq0'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'twitterSignIn' => ['privates', 'App\\RegisterLogin\\TwitterSignIn', 'getTwitterSignInService.php', true],
], [
    'twitterSignIn' => 'App\\RegisterLogin\\TwitterSignIn',
]);
