<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.errored..service_locator.yfEj2hU.App\Entity\BonusValue' shared service.

include_once \dirname(__DIR__, 4).'/src/Entity/BonusValue.php';

return $this->privates['.errored..service_locator.yfEj2hU.App\\Entity\\BonusValue'] = new \App\Entity\BonusValue();
