<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\EntityListener\BonusListener' shared autowired service.

include_once \dirname(__DIR__, 4).'/src/EntityListener/BonusListener.php';

return $this->privates['App\\EntityListener\\BonusListener'] = new \App\EntityListener\BonusListener();
