<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\BonusRendering\BonusRenderManager' shared autowired service.

include_once \dirname(__DIR__, 4).'/src/BonusRendering/BonusRenderManager.php';

return $this->privates['App\\BonusRendering\\BonusRenderManager'] = new \App\BonusRendering\BonusRenderManager(new RewindableGenerator(function () {
    yield 0 => ($this->privates['App\\BonusRendering\\CountryBonuses'] ?? $this->load('getCountryBonusesService.php'));
    yield 1 => ($this->privates['App\\BonusRendering\\GameBonuses'] ?? $this->load('getGameBonusesService.php'));
    yield 2 => ($this->privates['App\\BonusRendering\\IndexBonuses'] ?? $this->load('getIndexBonusesService.php'));
    yield 3 => ($this->privates['App\\BonusRendering\\SoftwareBonuses'] ?? $this->load('getSoftwareBonusesService.php'));
    yield 4 => ($this->privates['App\\BonusRendering\\ValueBonuses'] ?? $this->load('getValueBonusesService.php'));
}, 5));
