<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\EventSubscribers\ContactUsSubscriber' shared autowired service.

include_once \dirname(__DIR__, 4).'/src/EventSubscribers/ContactUsSubscriber.php';

return $this->privates['App\\EventSubscribers\\ContactUsSubscriber'] = new \App\EventSubscribers\ContactUsSubscriber(($this->privates['App\\Mailer\\Mailer'] ?? $this->load('getMailerService.php')));
