<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Feed\Importer\CasinosImporter' shared autowired service.

include_once \dirname(__DIR__, 4).'/src/Feed/Importer/FeedsParent.php';
include_once \dirname(__DIR__, 4).'/src/Feed/Importer/Importer.php';
include_once \dirname(__DIR__, 4).'/src/Feed/Importer/CasinosImporter.php';
include_once \dirname(__DIR__, 4).'/src/Feed/Downloader.php';
include_once \dirname(__DIR__, 4).'/src/ElasticSearch/ElasticSearch.php';

return $this->privates['App\\Feed\\Importer\\CasinosImporter'] = new \App\Feed\Importer\CasinosImporter(($this->privates['App\\Feed\\Downloader'] ?? ($this->privates['App\\Feed\\Downloader'] = new \App\Feed\Downloader($this->getEnv('FEED_TOKEN')))), ($this->privates['App\\ElasticSearch\\ElasticSearch'] ?? ($this->privates['App\\ElasticSearch\\ElasticSearch'] = new \App\ElasticSearch\ElasticSearch($this->getEnv('ELASTICSEARCH_SERVER')))), ($this->services['doctrine.orm.default_entity_manager'] ?? $this->getDoctrine_Orm_DefaultEntityManagerService()), (\dirname(__DIR__, 4).'/public'.$this->getEnv('string:UPLOAD_PATH').'/casino/'), ($this->privates['App\\Mailer\\Mailer'] ?? $this->load('getMailerService.php')), ($this->services['cache.app'] ?? $this->getCache_AppService()));
