<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Repository\CountryRepository' shared autowired service.

include_once \dirname(__DIR__, 4).'/src/Repository/CountryRepository.php';

return $this->privates['App\\Repository\\CountryRepository'] = new \App\Repository\CountryRepository(($this->services['doctrine'] ?? $this->getDoctrineService()));
