<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\EntityListener\CountryListListener' shared autowired service.

include_once \dirname(__DIR__, 4).'/src/EntityListener/CountryListListener.php';

return $this->privates['App\\EntityListener\\CountryListListener'] = new \App\EntityListener\CountryListListener();
