<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\RegisterLogin\FacebookSignIn' shared autowired service.

include_once \dirname(__DIR__, 4).'/src/RegisterLogin/SocialInterface.php';
include_once \dirname(__DIR__, 4).'/src/RegisterLogin/FacebookSignIn.php';

return $this->privates['App\\RegisterLogin\\FacebookSignIn'] = new \App\RegisterLogin\FacebookSignIn($this->getEnv('FACEBOOK_APP_ID'), $this->getEnv('FACEBOOK_APP_SECRET'), $this->getEnv('FACEBOOK_REDIRECT_URI'), ($this->services['doctrine.orm.default_entity_manager'] ?? $this->getDoctrine_Orm_DefaultEntityManagerService()), ($this->services['request_stack'] ?? ($this->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack())));
