<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Command\ImportCommand' shared autowired service.

include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
include_once \dirname(__DIR__, 4).'/src/Command/ImportCommand.php';
include_once \dirname(__DIR__, 4).'/src/Feed/ImportManager.php';

$this->privates['App\\Command\\ImportCommand'] = $instance = new \App\Command\ImportCommand(new \App\Feed\ImportManager(new RewindableGenerator(function () {
    yield 0 => ($this->privates['App\\Feed\\Importer\\BankingOptionsImporter'] ?? $this->load('getBankingOptionsImporterService.php'));
    yield 1 => ($this->privates['App\\Feed\\Importer\\BestCasinosImporter'] ?? $this->load('getBestCasinosImporterService.php'));
    yield 2 => ($this->privates['App\\Feed\\Importer\\BonusRestrictedCountriesImporter'] ?? $this->load('getBonusRestrictedCountriesImporterService.php'));
    yield 3 => ($this->privates['App\\Feed\\Importer\\BonusesImporter'] ?? $this->load('getBonusesImporterService.php'));
    yield 4 => ($this->privates['App\\Feed\\Importer\\CasinoBankingsImporter'] ?? $this->load('getCasinoBankingsImporterService.php'));
    yield 5 => ($this->privates['App\\Feed\\Importer\\CasinoCurrenciesImporter'] ?? $this->load('getCasinoCurrenciesImporterService.php'));
    yield 6 => ($this->privates['App\\Feed\\Importer\\CasinoLanguagesImporter'] ?? $this->load('getCasinoLanguagesImporterService.php'));
    yield 7 => ($this->privates['App\\Feed\\Importer\\CasinoRestrictedCountriesImporter'] ?? $this->load('getCasinoRestrictedCountriesImporterService.php'));
    yield 8 => ($this->privates['App\\Feed\\Importer\\CasinoSoftwareImporter'] ?? $this->load('getCasinoSoftwareImporterService.php'));
    yield 9 => ($this->privates['App\\Feed\\Importer\\CasinosImporter'] ?? $this->load('getCasinosImporterService.php'));
    yield 10 => ($this->privates['App\\Feed\\Importer\\CasinosJurisdictionsImporter'] ?? $this->load('getCasinosJurisdictionsImporterService.php'));
    yield 11 => ($this->privates['App\\Feed\\Importer\\CountryGroupsImporter'] ?? $this->load('getCountryGroupsImporterService.php'));
    yield 12 => ($this->privates['App\\Feed\\Importer\\CurrenciesImporter'] ?? $this->load('getCurrenciesImporterService.php'));
    yield 13 => ($this->privates['App\\Feed\\Importer\\LanguagesImporter'] ?? $this->load('getLanguagesImporterService.php'));
    yield 14 => ($this->privates['App\\Feed\\Importer\\NoDepositCodesImporter'] ?? $this->load('getNoDepositCodesImporterService.php'));
    yield 15 => ($this->privates['App\\Feed\\Importer\\RegionsImporter'] ?? $this->load('getRegionsImporterService.php'));
    yield 16 => ($this->privates['App\\Feed\\Importer\\SoftwareImporter'] ?? $this->load('getSoftwareImporterService.php'));
}, 17)), ($this->services['doctrine.orm.default_entity_manager'] ?? $this->getDoctrine_Orm_DefaultEntityManagerService()));

$instance->setName('app:import');

return $instance;
