<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Repository\LikeAndPostTypeRepository' shared autowired service.

include_once \dirname(__DIR__, 4).'/src/Repository/LikeAndPostTypeRepository.php';

return $this->privates['App\\Repository\\LikeAndPostTypeRepository'] = new \App\Repository\LikeAndPostTypeRepository(($this->services['doctrine'] ?? $this->getDoctrineService()));
