<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Aweber\MyApp' shared autowired service.

include_once \dirname(__DIR__, 4).'/src/Aweber/MyApp.php';

return $this->privates['App\\Aweber\\MyApp'] = new \App\Aweber\MyApp($this->getEnv('AWEBBER_CONSUMER_KEY'), $this->getEnv('AWEBBER_CONSUMER_SECRET'), $this->getEnv('AWEBBER_ACCES_TOKEN'), $this->getEnv('AWEBBER_ACCES_SECRET'), $this->getEnv('AWEBBER_SUBSCRIBERS_LIST'));
