<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\EventListener\NewNoDepositBonusEventSubscriber' shared autowired service.

include_once \dirname(__DIR__, 4).'/src/EventListener/NewNoDepositBonusEventSubscriber.php';

return $this->privates['App\\EventListener\\NewNoDepositBonusEventSubscriber'] = new \App\EventListener\NewNoDepositBonusEventSubscriber(($this->services['doctrine.orm.default_entity_manager'] ?? $this->getDoctrine_Orm_DefaultEntityManagerService()), ($this->privates['App\\Mailer\\Mailer'] ?? $this->load('getMailerService.php')), ($this->services['templating'] ?? $this->load('getTemplatingService.php')), ($this->privates['App\\Utils\\Locator'] ?? $this->load('getLocatorService.php')));
