<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Repository\NoDepositBonusMailsRepository' shared autowired service.

include_once \dirname(__DIR__, 4).'/src/Repository/NoDepositBonusMailsRepository.php';

return $this->privates['App\\Repository\\NoDepositBonusMailsRepository'] = new \App\Repository\NoDepositBonusMailsRepository(($this->services['doctrine'] ?? $this->getDoctrineService()));
