<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\SocialRegister\SocialRegister' shared autowired service.

include_once \dirname(__DIR__, 4).'/src/SocialRegister/SocialRegister.php';

return $this->privates['App\\SocialRegister\\SocialRegister'] = new \App\SocialRegister\SocialRegister($this->getEnv('TWITTER_CONSUMER_KEY'), $this->getEnv('TWITTER_CONSUMER_SECRET'), $this->getEnv('TWITTER_REDIRECT_URI'), $this->getEnv('FACEBOOK_APP_ID'), $this->getEnv('FACEBOOK_APP_SECRET'), $this->getEnv('FACEBOOK_REDIRECT_URI'));
