<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Repository\ScreenshotsRepository' shared autowired service.

include_once \dirname(__DIR__, 4).'/src/Repository/ScreenshotsRepository.php';

return $this->privates['App\\Repository\\ScreenshotsRepository'] = new \App\Repository\ScreenshotsRepository(($this->services['doctrine'] ?? $this->getDoctrineService()));
