<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Encoders\SaltMaker' shared autowired service.

include_once \dirname(__DIR__, 4).'/src/Encoders/SaltMaker.php';

return $this->privates['App\\Encoders\\SaltMaker'] = new \App\Encoders\SaltMaker();
