<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\EntityListener\UserListener' shared autowired service.

include_once \dirname(__DIR__, 4).'/src/EntityListener/UserListener.php';
include_once \dirname(__DIR__, 4).'/vendor/symfony/filesystem/Filesystem.php';

return $this->privates['App\\EntityListener\\UserListener'] = new \App\EntityListener\UserListener((\dirname(__DIR__, 4).'/public'.$this->getEnv('string:UPLOAD_PATH').'/user/'), $this->getEnv('string:UPLOAD_PATH').'/user/', ($this->services['filesystem'] ?? ($this->services['filesystem'] = new \Symfony\Component\Filesystem\Filesystem())), ($this->privates['App\\Aweber\\MyApp'] ?? $this->load('getMyAppService.php')));
