<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHIe2GGh\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHIe2GGh/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHIe2GGh.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHIe2GGh\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerHIe2GGh\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'HIe2GGh',
    'container.build_id' => '0dd59be7',
    'container.build_time' => 1580476016,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHIe2GGh');
